### ISSUE TITLE
Release not found

### ISSUE THREAD

**Issue by mkokho** [pact-foundation/pact-ruby-standalone#112]
Hello,

I tried to download an executable for windows x86_64, but the response returned "Not Found"

This is the url: https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v2.0.2/pact-2.0.2-windows-x86_64.tar.gz

![image](https://github.com/pact-foundation/pact-ruby-standalone/assets/10990119/66338c6b-4e34-4636-bf74-f89d85c7ae08)

**Comment by mkokho** [comment]
Found the correct URL at the bottom, the file ends with `.zip`, not `.tar.gz`

https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v2.0.2/pact-2.0.2-windows-x86_64.zip

**Comment by mefellows** [comment]
Ah, looks like the release notes are no longer correct - it should be zip as noted. This must have changed recently:

<img width="1281" alt="Screenshot 2023-06-27 at 3 23 10 pm" src="https://github.com/pact-foundation/pact-ruby-standalone/assets/53900/37e9e1bd-b17b-47e5-b057-cdf023e51888">

**Comment by bethesque** [comment]
@YOU54F when you're back, could you update the docs for this? 🙏🏽

**Comment by YOU54F** [comment]
Thanks for raising @mkokho - Have got an updated PR and will retrospectively update the exist release note.
