### ISSUE TITLE
single file executables

### ISSUE THREAD

**Issue by YOU54F** [pact-foundation/pact-ruby-standalone#118]
Hey hey,

Currently we use traveling-ruby to package up our ruby tools into a zipped folder for distribution.

There are few projects which are designed to also support packaging ruby, but using alternate methods, provide a ruby runtime, but as a single executable, that is unpacked into a temp dir when run.

- [Ocra](https://github.com/larsch/ocra)
  - [Ocran](https://github.com/larsch/ocra/issues/193#issuecomment-1549863387) - Ruby 3.2 compatible fork
- [Rb2exe](https://github.com/thecodecrate/rb2exe)
- [Ruby-packer](https://github.com/pmq20/ruby-packer)

I've been playing out with a few of them and using the work/knowledge I've gained from traveling-ruby to get them up to date and working to help the Ruby community out, and possibly make things simpler for our users when they are starting.

Also I got annoyed at no docker in non linux CI workflows, and kept hammering PactFlow during integration tests, so a nice self contained broker, you can start up on the command line, without Docker was one of my side aims

## Windows

Create self extracting pact executables, with native extensions for windows

- https://github.com/YOU54F/pact-ruby-standalone/releases/tag/v2.4.0-alpha

## MacOS / Linux

- Created a traveling-ruby distro with all the pact packages preinstalled, with native gems for macos/linux arm64/amd64
  - https://github.com/YOU54F/traveling-ruby/releases/tag/rel-20230803-pact
- made the pact broker available as a homebrew formula
  - https://github.com/YOU54F/homebrew-pact/blob/master/Formula/pact_broker.rb
- made the pact broker available as a github action
  - https://github.com/YOU54F/pact-cli-action/blob/feat/pact_broker/.github/workflows/pact_broker.yml
  
  
rb2exe - this uses traveling-ruby and packages into a single file
  
- Updated to use latest traveling-ruby
  - https://github.com/YOU54F/rb2exe/pull/1
- Updated to use latest traveling-pact package
  - https://github.com/YOU54F/rb2exe/pull/2

**Comment by YOU54F** [comment]
Awwww yeaaaah 🚀 ruby packer packing ruby in alpine. It be a chonkie boi tho

<img width="1054" alt="Screenshot 2023-08-16 at 22 57 21" src="https://github.com/pact-foundation/pact-ruby-standalone/assets/19932401/d575746e-884a-4dc0-81da-b087cdecd065">

**Comment by bethesque** [comment]
These are beautiful, but given we're trying to remove the ruby-standalone and use the rust impl instead, what is our usecase for these different packages?

**Comment by YOU54F** [comment]
Soooo, there are a few reasons why I wandered down this rabbit hole. Given that we are moving (or have moved) away from the Ruby ecosystem as the heart of Pact, it would be nice to have a nice little farewell party for all things Ruby 

## Pact Broker in a box - For use in testing environments that don't have Docker

- Ability to spin up a test Pact Broker, without needing to install Ruby/Docker
  - CirrusCI MacOS & GitHub Actions MacOS / Windows runners, don't have access to Docker - and therefore had never ran before
    - For confidence whilst I was implementing the FFI layer into Pact-Python, I wanted to confidence that these examples would work cross-platform.
  - Pact python e2e examples use a Pact Broker
    - We test 6 python versions, across 3 operating systems and two processor types, so we have a large amount of Pacts being published in a short space of time
    -  In order to make the e2e tests run in CI, I switched out conditionally to use the self hosted Pact Broker provided by PactFlow but was being rate limited

## Gift back to the Ruby Community

  - The Ruby community has never had first class support for producing standalone packages, other than community impls like Ruby-Packer, Traveling-Ruby and Ocra. These have been unmaintained for some time.
  - It's nice to take the learnings from traveling Ruby and apply them to the Ruby packaging eco-system, before I depart into the world of Rust.
  
## Better windows support

  - Currently traveling-ruby doesn't support native gems for Windows
  - Long path issues, issues with paths in spaces (I believe rubyc will be unaffected by these)
  
## Pact in a box - consolidated tooling

  - The idea of Pact in a box, you can download one package, which gives you everything you need to get quickly started
  - Some thoughts around consolidated bundling here https://github.com/pact-foundation/pact-ruby-standalone/pull/117
  
## Phased replacement of ruby cli tooling
  - I'm unsure if we would like to duplicate or move any of the broker client functionality over to Rust. (the other gems don't make sense, as they already have equivs - mock/stub server & verifier)
    - If we did, it would be nice to have the ability to switch between a rust impl or ruby impl. Maybe a rust bin entry point.

## All the cool kids love Alpine

- Traveling-ruby is built on centos7 and uses glibc, which means Alpine users require gcompat or similar libs in order to use the linux executables. 
  - If we could build traveling-ruby against Alpine distros (or Rubyc), then we can provide a musl native ruby experience for Alpine users.

**Comment by YOU54F** [comment]
Also just to add, as an additional aside. The Pact Broker uses a large amount of native gems, of which I hadn't really tested with Traveling-Ruby and it was a big selling point of the packaging system.

It irked me a little bit that that I hadn't been able to cover/test that case, so I decided to ensure that it could build and package native gems, and what better way than to test something that I know and love, our Pact Broker!
