### ISSUE TITLE
Recommended approach can-i-deploy

### ISSUE THREAD

**Issue by leandroramello** [pact-foundation/pact-ruby-standalone#13]
Hello.
Im getting an error when run:

pact-broker can-i-deploy --pacticipant documentmanager --version 1.2.7 --to dev1-TESTING --broker-base-url https://pactstest.xxx.net

The console is reporting that:

{"message":"Could not find version with tag \"dev1-TESTING\" for token","backtrace":["/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.13.1/lib/pact_broker/matrix/repository.rb:85:in `block in look_up_versions_for_latest_and_tag'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.13.1/lib/pact_broker/matrix/repository.rb:81:in `collect'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.13.1/lib/pact_broker/matrix/repository.rb:81:in `look_up_versions_for_latest_and_tag'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.13.1/lib/pact_broker/matrix/repository.rb:117:in `apply_latest_and_tag_to_inferred_selectors'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.13.1/lib/pact_broker/matrix/repository.rb:73:in `resolve_selectors'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.13.1/lib/pact_broker/matrix/repository.rb:25:in `find'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.13.1/lib/pact_broker/matrix/service.rb:12:in `find'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.13.1/lib/pact_broker/api/resources/matrix.rb:45:in `lines'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.13.1/lib/pact_broker/api/resources/matrix.rb:37:in `to_json'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/webmachine-1.5.0/lib/webmachine/decision/flow.rb:475:in `o18'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/webmachine-1.5.0/lib/webmachine/decision/fsm.rb:31:in `block (2 levels) in run'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/webmachine-1.5.0/lib/webmachine/decision/fsm.rb:51:in `handle_exceptions'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/webmachine-1.5.0/lib/webmachine/decision/fsm.rb:31:in `block in run'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/webmachine-1.5.0/lib/webmachine/decision/fsm.rb:29:in `loop'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/webmachine-1.5.0/lib/webmachine/decision/fsm.rb:29:in `run'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/webmachine-1.5.0/lib/webmachine/dispatcher.rb:46:in `block in dispatch'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/as-notifications-1.0.1/lib/as/notifications.rb:161:in `instrument'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/webmachine-1.5.0/lib/webmachine/events.rb:75:in `instrument'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/webmachine-1.5.0/lib/webmachine/dispatcher.rb:45:in `dispatch'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/webmachine-1.5.0/lib/webmachine/adapters/rack.rb:68:in `call'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.13.1/lib/rack/pact_broker/database_transaction.rb:29:in `call_without_transaction'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.13.1/lib/rack/pact_broker/database_transaction.rb:20:in `call'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.13.1/lib/rack/pact_broker/no_auth.rb:9:in `call'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:153:in `call'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/cascade.rb:33:in `block in call'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/cascade.rb:24:in `each'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/cascade.rb:24:in `call'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:68:in `block in call'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `each'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `call'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/static.rb:149:in `call'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.13.1/lib/rack/hal_browser/redirect.rb:20:in `call'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.13.1/lib/rack/pact_broker/convert_file_extension_to_accept_header.rb:22:in `call'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/static.rb:149:in `call'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/static.rb:149:in `call'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.13.1/lib/rack/pact_broker/add_pact_broker_version_header.rb:14:in `call'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.13.1/lib/rack/pact_broker/store_base_url.rb:10:in `call'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.13.1/lib/rack/pact_broker/invalid_uri_protection.rb:16:in `call'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/rack-protection-2.0.0/lib/rack/protection/xss_header.rb:18:in `call'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/rack-protection-2.0.0/lib/rack/protection/json_csrf.rb:26:in `call'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/rack-protection-2.0.0/lib/rack/protection/frame_options.rb:31:in `call'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:153:in `call'","/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.13.1/lib/pact_broker/app.rb:55:in `call'","/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'","/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'","/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'","/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'","/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'"]}

And im seeing a pact with the tag dev1-TESTING in my pact broker.
![captura](https://user-images.githubusercontent.com/19871317/36583435-01b30d48-1876-11e8-8c6e-8f468b0b93e6.PNG)

What happens?

Thank you so much!!

**Comment by bethesque** [comment]
When you use `--to TAG`, `can-i-deploy` finds the latest version with that tag name for all the _other applications_ that have a pact with the application you are about to deploy. For example, if you are about to deploy to `prod`, you need to know that the app that you're about to deploy is compatible with all the other application versions that are currently in `prod`.

Not that the error message says `Could not find version with tag "dev1-TESTING" for token`. I assume there is a pact with a service called `token`. This is the pacticipant that doesn't have a version with the tag `dev1-TESTING`.

**Comment by leandroramello** [comment]
mmm :S
But, in this case, token is a provider of documentmanager.
The providers must tag something?
I understood that only published pacts can be tagged and only his creator (consumer) can tag it.
Thanks!

**Comment by bethesque** [comment]
You get a 405 for the first link because GET is not implemented, and a forbidden for the second probably because you're not authenticated. The code is working fine.

Yes, token is the provider. Why do you think only pacts can be tagged? It's actually the pacticipant version that is tagged, not the pact, and you can tag both consumer and provider versions. When you use can-i-deploy, you need to tell the tool both the consumer version you're about to deploy AND the provider version that already is deployed in that environment. You can give the provider version explicitly like this:

    pact-broker can-i-deploy --pacticipant documentmanager --version 1.2.7 --pacticipant token --version 0.4.5

OR

you can tag the provider version with the name of the environment eg. `prod` by doing a `PUT /pacticipants/token/versions/0.4.5/tags/prod`. Then you tell `can-i-deploy` to check if version 1.2.7 is compatible with the latest `prod` version of all the other applications it has pacts with by doing:

    pact-broker can-i-deploy --pacticipant documentmanager --version 1.2.7 --to prod

Please have a read of the [overview](https://github.com/pact-foundation/pact_broker/wiki/Overview) in the wiki.

**Comment by leandroramello** [comment]
Hi!
I was not correctly understanding the behavior.
You have solved my doubts.
Thanks!!
