### ISSUE TITLE
Properly uninstall the rdoc gem instead of rm lib

### ISSUE THREAD

**Issue by milda-a** [pact-foundation/pact-ruby-standalone#142]
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [x] Upgraded to the latest version of the relevant libraries
* [x] Checked to see if the issue has already been raised

## Software versions

* **pact-ruby-standalone:** eg 2.4.2

## Expected behaviour

Rdoc gem properly removed from the binaries, without any leftover files.

## Actual behaviour

Rdoc gem has some hanging files which flag up security.

## Steps to reproduce

Rdoc is being removed in pact here:
 https://github.com/pact-foundation/pact-ruby-standalone/blob/abeee3dc705df36bad560fc53b71600e8fde7baa/tasks/package.rake#L196
And we remove the .gemspec file, however, security is still flagging it up, so, if possible, please remove the gem properly with `gem uninstall`.

## Relevent log files

Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link from a gist).

**Comment by YOU54F** [comment]
which files are security flagging up?

the default gemspec is being deleted here 

https://github.com/pact-foundation/pact-ruby-standalone/pull/140

as per the previous issue

https://github.com/pact-foundation/pact-ruby-standalone/issues/134#issuecomment-2060734687

but this is yet to be released (should be releasing shortly)

**Comment by YOU54F** [comment]
we package on a single machine so cannot execute the end user packages without using separate runners

**Comment by mefellows** [comment]
It's worth noting that rdoc is included in the Ruby distribution itself, which is why I think it's been removed this way. 

I know your security tool is flagging it as an issue because there is a vulnerability in it, but I'd argue the vulnerability itself is not a practical problem for any users of this tool. That is, the circumstances that would make it an actual threat are not relevant here.
