### ISSUE TITLE
Problem running standalone version on Docker

### ISSUE THREAD

**Issue by nicpillinger** [pact-foundation/pact-ruby-standalone#17]
Hi Beth, have tried both the standalone executable (linux x64) and the ruby gem. It currently appears to fail with a missing dependency on rake?
https://www.dropbox.com/s/qi4prx2ce3e768b/Screenshot%202018-05-22%2008.45.45.png?dl=0

If I add rake to my Gemfile and bundle install it fixes the problem.

**Comment by bethesque** [comment]
Hm. That's strange. It works on mac.

<img width="1304" alt="screen shot 2018-05-23 at 1 21 09 pm" src="https://user-images.githubusercontent.com/446228/40401939-69fdd34a-5e8c-11e8-8d08-8049dbb10273.png">

I wonder if it's a linux issue. I'll pull out my linux laptop and give it a try.

**Comment by bethesque** [comment]
![pact](https://user-images.githubusercontent.com/446228/40402199-9b60b60e-5e8d-11e8-9a0a-34d960f0b711.png)

Nope. Works on my linux machine too. And the gem.

![pactbrokerclient](https://user-images.githubusercontent.com/446228/40402267-fc42f464-5e8d-11e8-87f2-01145706a86d.png)

I'm a bit confused by your image though. Why are you doing a bundle install from within what looks like the standalone directory? Can you provide a script that recreates your error? Preferably in a github repo that runs a build on travis?

**Comment by nicpillinger** [comment]
Hi, yes its a docker image which is why it looks a bit odd. Possibly it works as rake is already globally installed for you so is available? I'll try and reproduce.

**Comment by bethesque** [comment]
I tried uninstalling rake, and it still works. You shouldn't need to run bundle at all for the standalone. It's just that - a standalone. It shouldn't know or care about any ruby installation outside it (unless there's a bug in Travelling Ruby itself)

**Comment by nicpillinger** [comment]
@bethesque the screen shot was actually from me just using the pact_broker-client gem. Which I have got working by adding rake to my Gemfile as well. I'll try and reproduce the issue for the standalone ruby - it could be that rake is being added at the system level on some builds.

**Comment by nicpillinger** [comment]
@bethesque here's a Dockerfile which demonstrates problems with running the standalone stuff in docker. I haven't investigated yet but it could just be that traveling ruby doesn't support being run in an alpine container https://gist.github.com/nicpillinger/5385583c4c6e3c35f630e1862566cc1d

**Comment by bethesque** [comment]
No, it doesn't support being run on alpine out of the box. You need to do this: https://github.com/pact-foundation/pact-ruby-standalone/wiki/Using-the-pact-ruby-standalone-with-Alpine-Linux-Docker

However, I'm not sure whether the symptom your seeing is due to that. Give it a try and see.

**Comment by azakordonets** [comment]
I'm also having problems running standalone pact in Docker : 
```
FROM ruby:2-alpine

RUN apk add --no-cache --virtual curl build-dependencies build-base \
      && curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.69.0/pact-1.69.0-linux-x86_64.tar.gz \
      && tar xzf pact-1.69.0-linux-x86_64.tar.gz

WORKDIR pact/bin
```

When i run inside the container `./pact-message --help run` i get this error : 
```
./pact-message: exec: line 28: /pact/lib/ruby/bin/ruby: not found

```

**Comment by mefellows** [comment]
You'll need bash too I'm pretty sure

**Comment by azakordonets** [comment]
Alpine has sh, so that should not be a problem. The error i showed is from the inside of the container. But you can also build an image and run it interactively - error will be the same

**Comment by mefellows** [comment]
I understand it has ash, but it _needs_ bash. There are things in those
bootstrap scripts that ash doesn't support. I'll see about updating our
docker docs today on docs.pact.io.

**Comment by azakordonets** [comment]
Running
```
FROM ruby:2-alpine

RUN apk add --no-cache --virtual build-dependencies build-base
RUN apk --no-cache add ca-certificates wget bash \
  && wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
  && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-2.29-r0.apk \
  && apk add glibc-2.29-r0.apk
```
works. Thanks for updating documentation. I can run standalone version of the pact. 

Unfortunately I can't copy pact executables to `/usr/loca/bin` because when i try to run it from there - i get an error : 
```
/ # cp -R pact/* /usr/local/bin
/ # ls -la /usr/local/bin
total 36
drwxr-xr-x    5 root     root          4096 Jul 22 04:13 .
drwxr-xr-x    7 root     root          4096 Jul 22 04:09 ..
-rw-r--r--    1 root     root         15485 Jul 22 04:13 README.md
drwxr-xr-x    2 root     root          4096 Jul 22 04:13 bin
drwxr-xr-x    5 root     root          4096 Jul 22 04:13 lib
drwxr-xr-x    2 root     root          4096 Jul 22 04:13 pacts
/ # /usr/local/bin/bin/pact
Commands:
  pact docs                                  # Generate Pact documentation in markdown
  pact help [COMMAND]                        # Describe available commands or one specific command
  pact verify -h, --pact-helper=PACT_HELPER  # Verify a pact

/ # cp /usr/local/bin/bin/pact /usr/local/bin
/ # pact
/usr/local/bin/pact: exec: line 28: /usr/local/lib/ruby/bin/ruby: not found
```

**Comment by bethesque** [comment]
Try symlinking it instead. The `pact` executable requires all the support files that get unpackaged with it, and just moving the `pact` file will break things.

**Comment by azakordonets** [comment]
When i do : 
```
 ln -s pact/bin/pact /bin
```

Then i get `symbolic link loop error`
```
/ # pact
/bin/sh: pact: Symbolic link loop
```

**Comment by bethesque** [comment]
I'm not sure why that would be. This works fine on my mac `ln -s pact/bin/pact /usr/local/bin`.

**Comment by azakordonets** [comment]
You're right ! I missed one slash in `ln -s /pact/bin/pact` . Ok, for everyone interested - this is how you can run standalone pact in alpine docker : 
```
FROM alpine as pact

RUN apk --no-cache add ca-certificates wget bash \
  && wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
  && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-2.29-r0.apk \
  && apk add glibc-2.29-r0.apk

RUN wget https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.69.0/pact-1.69.0-linux-x86_64.tar.gz \
    && tar xzf pact-1.69.0-linux-x86_64.tar.gz \
    && rm -rf pact-1.69.0-linux-x86_64.tar.gz

RUN ln -s /pact/bin/pact /usr/local/bin \
    && ln -s /pact/bin/pact-broker /usr/local/bin \
    && ln -s /pact/bin/pact-message /usr/local/bin \
    && ln -s /pact/bin/pact-mock-service /usr/local/bin \
    && ln -s /pact/bin/pact-provider-verifier /usr/local/bin \
    && ln -s /pact/bin/pact-publish /usr/local/bin \
    && ln -s /pact/bin/pact-stub-service /usr/local/bin
```
@nicpillinger i think this issue can be closed.

**Comment by nicpillinger** [comment]
thanks @azakordonets, looks like it. to be honest, I managed to work around it in the end so never followed up on the issue. I think the main issue is that alpine doesn't use glibc and loads of things (inc. pact/ruby tools etc.) rely on the glibc toolchain being in place.
