### ISSUE TITLE
Support of Ruby 2.2 has ended

### ISSUE THREAD

**Issue by springerigor** [pact-foundation/pact-ruby-standalone#21]
For example version 3.7 of alpine Linux Docker images has already removed it. Are there any blockers for bumping up Ruby version within `pact-ruby-standalone`?

**Comment by bethesque** [comment]
Yes, unfortunately. Travelling Ruby, which we use to package the code, only supports 2.2. People have attempted to do provide a more recent package, but nobody has completed the work. The lack of support should not impact anything that I can think of though.

**Comment by springerigor** [comment]
Thanks for the answer 👍 I'm closing the issue.
