### ISSUE TITLE
Problem running the standalone in windows---loadError

### ISSUE THREAD

**Issue by Blankofnothing** [pact-foundation/pact-ruby-standalone#24]
Hi,everybody
Do I  need to install Ruby to use Pact standalone executables？
when I follow the step to install executables 
I use the command pact-mock-service.bat --hlep start
then I got the Loaderror

D:\OJ工程\eclipse\pact\bin>pact-mock-service.bat --help start
<internal:gem_prelude>:1:in `require': cannot load such file -- rubygems.rb (LoadError)
        from <internal:gem_prelude>:1:in `<compiled>'

I 'm new to ruby,thanks to you advanced

**Comment by mefellows** [comment]
You shouldn't have to, no. 

It could be

 a) windows related 
 b) Unicode character related

Perhaps try running it using onky ASCII characters in the path?

**Comment by Blankofnothing** [comment]
> You shouldn't have to, no.
> 
> It could be
> 
> a) windows related
> b) Unicode character related
> 
> Perhaps try running it using onky ASCII characters in the path?

Thanks a lot ,it works now
