### ISSUE TITLE
Problem running standalone version on Linux 64

### ISSUE THREAD

**Issue by jesus-medinilla** [pact-foundation/pact-ruby-standalone#25]
Hi,

I'm trying to run this command from a Debian image:

pact-provider-verifier --pact-broker-base-url $PACT_BROKER_URL --provider-base-url *** --provider users_http_provider --provider-app-version=0.0.1-SNAPSHOT --publish-verification-results=false

but what I'm getting from the response is this error:

/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.8.0/lib/pact/matching_rules/v3/merge.rb:119:in `block (2 levels) in log_ignored_rules': undefined method `any?' for "AND":String (NoMethodError)
        from /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.8.0/lib/pact/matching_rules/v3/merge.rb:118:in `each'
        from /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.8.0/lib/pact/matching_rules/v3/merge.rb:118:in `block in log_ignored_rules'
        from /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.8.0/lib/pact/matching_rules/v3/merge.rb:117:in `each'

This errors happens because of the invokation of _any?_ method on a string value, which is not  supported in this ruby version.

I'm using pact-1.61.2 on Linux 64.

Thanks

**Comment by mefellows** [comment]
Can you please share the pact file or provide a repro for us to identify and fix?

**Comment by bethesque** [comment]
This is fixed in version 1.63.0 of the standalone. @mboudreau could you update this please, as Matt is travelling at the moment.

**Comment by jesus-medinilla** [comment]
Thanks!
