### ISSUE TITLE
Problem with ASCII-8BIT body encoding

### ISSUE THREAD

**Issue by rawphp** [pact-foundation/pact-ruby-standalone#27]
I'm trying to verify a provider that uses a SOAP api and returns the body as XML encoded in ASCII-8BIT.

`
Failures:

  1) Verifying a pact between dhl-paket-integration and dhl-paket Given   with POST /services/sandbox/soap returns a response which has a matching body
     Failure/Error: expect(response_body).to match_term expected_response_body, diff_options, example

     Encoding::UndefinedConversionError:
       "\xC3" from ASCII-8BIT to UTF-8

`

Do you have any plans to support this encoding type?

**Comment by bethesque** [comment]
No, I'm sorry. The JSON file encoding is UTF-8, so I don't know how we'd achieve the serialization of an ASCII-8BIT character within that.
