### ISSUE TITLE
Lack of support for PACT Spec v3

### ISSUE THREAD

**Issue by eamodeorubio** [pact-foundation/pact-ruby-standalone#31]
It seems the version of `pact-mock-service` is currently `2.12.0` that does not support spec v3 of PACT, while the latest `pact-mock-service` does.

Could you please make a new release for `pact-ruby-standalone` with the latest gem versions. I guess after that other projects, like `pact-js` would need to be upgraded.

**Comment by mefellows** [comment]
Hi @eamodeorubio, to the best of my knowledge, the Ruby lib doesn't actually support the full v3 spec yet. It does support a small subset of it, enough to do message support (which is included in Pact JS and Pact Go for example).

Where did you get the impression that it does? This might be an issue with docs etc.

**Comment by eamodeorubio** [comment]
You are right @mefellows, I got the wrong impression from [the README.md of pact-mock_service](https://github.com/pact-foundation/pact-mock_service#mock-service-usage). The "Mock service usage"  shows an example of the help output from the CLI, and it says nothing about "only supported version 1 and 2" like in the other versions. That's why I assumed that it does support v3.

It seems that that example is wrong, as shown in the source code: https://github.com/pact-foundation/pact-mock_service/blob/master/lib/pact/mock_service/cli.rb#L23

**Comment by bethesque** [comment]
@eamodeorubio the only reason it's not done is that we all have limited free time, and we're spending it on the Pact Broker + Pactflow at the moment. It will happen eventually! I'll make it clearer in the help output that v3 is not fully supported yet.
