### ISSUE TITLE
Error parsing json in 'Reify' when running from Linux 64

### ISSUE THREAD

**Issue by bartschotten** [pact-foundation/pact-ruby-standalone#32]
I'm running into a problem when testing messages with pact-net, and the output seems to suggest the problem originates in the ruby core.

I've got a test that succeeds when running from Windows but fails when running from Linux because it can't parse json. This is a consumer test so I guess the json is generated during the test and not input *for* the test.

`/mnt/c/Repos/Pact-Net/Samples/MessageZooEvents/ZooEventsConsumer.Tests/bin/Debug/netcoreapp2.2/pact-linux-x86_64/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /mnt/c in PATH, mode 040777
/mnt/c/Repos/Pact-Net/Samples/MessageZooEvents/ZooEventsConsumer.Tests/bin/Debug/netcoreapp2.2/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/json-2.1.0/lib/json/common.rb:156:in 'parse': 757: unexpected token at ''{id:{json_class:Pact::SomethingLike,contents:2},name:{json_class:Pact::SomethingLike,contents:Terence},type:{json_class:Pact::SomethingLike,contents:Giraffe}}'' (JSON::ParserError)
        from /mnt/c/Repos/Pact-Net/Samples/MessageZooEvents/ZooEventsConsumer.Tests/bin/Debug/netcoreapp2.2/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/json-2.1.0/lib/json/common.rb:156:in 'parse'
        from /mnt/c/Repos/Pact-Net/Samples/MessageZooEvents/ZooEventsConsumer.Tests/bin/Debug/netcoreapp2.2/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/json-2.1.0/lib/json/common.rb:335:in 'load'
        from /mnt/c/Repos/Pact-Net/Samples/MessageZooEvents/ZooEventsConsumer.Tests/bin/Debug/netcoreapp2.2/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-message-0.5.0/lib/pact/message/cli.rb:24:in 'reify'
        from /mnt/c/Repos/Pact-Net/Samples/MessageZooEvents/ZooEventsConsumer.Tests/bin/Debug/netcoreapp2.2/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/thor-0.20.0/lib/thor/command.rb:27:in 'run'
        from /mnt/c/Repos/Pact-Net/Samples/MessageZooEvents/ZooEventsConsumer.Tests/bin/Debug/netcoreapp2.2/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in 'invoke_command'
        from /mnt/c/Repos/Pact-Net/Samples/MessageZooEvents/ZooEventsConsumer.Tests/bin/Debug/netcoreapp2.2/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/thor-0.20.0/lib/thor.rb:387:in 'dispatch'
        from /mnt/c/Repos/Pact-Net/Samples/MessageZooEvents/ZooEventsConsumer.Tests/bin/Debug/netcoreapp2.2/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/thor-0.20.0/lib/thor/base.rb:466:in 'start'
        from /mnt/c/Repos/Pact-Net/Samples/MessageZooEvents/ZooEventsConsumer.Tests/bin/Debug/netcoreapp2.2/pact-linux-x86_64/lib/app/pact-message.rb:28:in '<main>'
Stack Trace:
   at PactNet.Core.PactCoreHost'1.Start() in /mnt/c/Repos/Pact-Net/PactNet/Core/PactCoreHost.cs:line 143
   at PactNet.PactMessage.Host.Commands.ReifyCommand.Execute() in /mnt/c/Repos/Pact-Net/PactNet/PactMessage/Host/Commands/ReifyCommand.cs:line 38
   at PactNet.PactMessage.MessagePact.VerifyConsumer[T](Action'1 messageHandler) in /mnt/c/Repos/Pact-Net/PactNet/PactMessage/MessagePact.cs:line 106
   at ZooEventsConsumer.Tests.SavePetsTests.Handle_WhenANonPetAnimalIsCreated_DoesNotSaveIt() in /mnt/c/Repos/Pact-Net/Samples/MessageZooEvents/ZooEventsConsumer.Tests/SavePetsTests.cs:line 68`

See also https://github.com/pact-foundation/pact-net/pull/175

**Comment by bethesque** [comment]
As I don't have a linux machine, and I don't know .net, can you provide a Docker image to reproduce this issue on @bartschotten

**Comment by bartschotten** [comment]
I'm trying to reproduce it without pact-net. I don't know Ruby and I'm struggling to get it to work under Linux... but are there any existing tests that I should try to run that might trigger this issue?

**Comment by bethesque** [comment]
Given that the code works on windows with pact-net and on linux with pact-js, I suspect the issue may in the parameter escaping in the pact-net code when on linux. In which case, reproducing it with the pact-net code is probably what we want. I'll just need some way to run it (docker or a travis/appveyor/other build).

**Comment by bartschotten** [comment]
It's a bit tricky to provide a way to reproduce it, since I've done some local hacking to get it to produce any output. Meanwhile, this is how the ruby core is actually called:

Windows: 
File: 
`C:\Repos\pact-net\Samples\MessageZooEvents\ZooEventsConsumer.Tests\bin\Release\netcoreapp2.2\\pact-win32\lib\ruby\bin.real\ruby.exe`
Arguments:
`-rbundler/setup -I"C:\Repos\pact-net\Samples\MessageZooEvents\ZooEventsConsumer.Tests\bin\Release\netcoreapp2.2\\pact-win32\lib\app\lib" "C:\Repos\pact-net\Samples\MessageZooEvents\ZooEventsConsumer.Tests\bin\Release\netcoreapp2.2\\pact-win32\lib\app\pact-message.rb" reify '{"id":{"json_class":"Pact::SomethingLike","contents":2},"name":{"json_class":"Pact::SomethingLike","contents":"Terence"},"type":{"json_class":"Pact::SomethingLike","contents":"Giraffe"}}'`

Linux:
File: 
`/mnt/c/Repos/pact-net/Samples/MessageZooEvents/ZooEventsConsumer.Tests/bin/Debug/netcoreapp2.2//pact-linux-x86_64/bin/pact-message`
Arguments:
`reify '{"id":{"json_class":"Pact::SomethingLike","contents":2},"name":{"json_class":"Pact::SomethingLike","contents":"Terence"},"type":{"json_class":"Pact::SomethingLike","contents":"Giraffe"}}'`

**Comment by bartschotten** [comment]
It turns out that indeed the command line argument for the reify script is interpreted differently between the two platforms. On Linux I (sort of) got it to work by escaping the double quotes and replacing the single quotes at the start and the end with double quotes.

I'll close this issue since it's not doesn't seem to be an issue that can be solved in ruby,
