### ISSUE TITLE
Doesn't handle being in a directory with spaces in the name on OS X

### ISSUE THREAD

**Issue by richard-reece** [pact-foundation/pact-ruby-standalone#37]
Grabbed the latest version, pact-1.67.0, and for "reasons" the download ended up in a directory called "pact 2". Attempting to run the programs inside that directory results in:
```
me@~/Downloads/pact 2/bin$ ./pact-broker can-i-deploy -h
/Users/me/Downloads/pact 2/lib/ruby/bin/ruby: line 14: 2/lib/ruby/lib/ruby/gems/2.2.0: No such file or directory
```

**Comment by bethesque** [comment]
Sorry, I only just saw this. What's the status?

**Comment by bethesque** [comment]
Sorry, I only just saw this. Will look into it.

**Comment by YOU54F** [comment]
Believe this is fixed now with changes incorporated in our traveling-ruby fork

<img width="1402" alt="Screenshot 2024-05-10 at 18 29 23" src="https://github.com/pact-foundation/pact-ruby-standalone/assets/19932401/2a4e831d-b1b6-4bf2-a6a6-1ed62e1d740c">
<img width="982" alt="Screenshot 2024-05-10 at 18 30 10" src="https://github.com/pact-foundation/pact-ruby-standalone/assets/19932401/9def5b76-f08c-4c9d-abbb-662cade182f7">
