### ISSUE TITLE
regexp in query matching doesn't work for pact-stub-service

### ISSUE THREAD

**Issue by kkadziolka** [pact-foundation/pact-ruby-standalone#38]
It seems that pact-stub-service  doesn't work with regexp in query matching and examples.

See example below (part of file) - pact-stub-service requires **sortOrder** to be equal **DESC**, and **sortField** equal to **string** instead of matchers defined below. In other case you will get 500
with body descrbing that all definied interactions don't match.

`"query": {
          "sortOrder": [
            "DESC"
          ],
          "sortField": [
            "string"
          ]
        },
"matchingRules": {
          "query": {
            "sortField": {
              "matchers": [
                {
                  "match": "regex",
                  "regex": ".*"
                }
              ],
              "combine": "AND"
            },
            "sortOrder": {
              "matchers": [
                {
                  "match": "regex",
                  "regex": "(ASC)|(DESC)"
                }
              ],
              "combine": "AND"
            }
          }`

**Comment by kkadziolka** [comment]
`"query": {
          "**sortOrder**": [
            "**DESC**"
          ],
          "**sortField**": [
            "**string**"
          ]
        },
"matchingRules": {
          "query": {
            "**sortField**": {
              "matchers": [
                {
                  "match": "**regex**",
                  "regex": ".*"
                }
              ],
              "combine": "AND"
            },
            "**sortOrder**": {
              "matchers": [
                {
                  "match": "**regex**",
                  "regex": "**(ASC)|(DESC)**"
                }
              ],
              "combine": "AND"
            }
          }`

**Comment by bethesque** [comment]
That's a v3 pact, and the Ruby stub server only supports v2 so far.
