### ISSUE TITLE
pact-publish cli tool produces ruby error with kernel-require.rb dependency when run.

### ISSUE THREAD

**Issue by heretogo** [pact-foundation/pact-ruby-standalone#39]
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [x] Upgraded to the latest version of the relevant libraries
* [x] Checked to see if the issue has already been raised
* [ ] Created an executable example that demonstrates the issue using either:
  * a Dockerfile
  * a fork of https://github.com/pact-foundation/pact-ruby-standalone-e2e-example
  * a Git repository with a Travis or Appveyor (or similar) build
  * a gist with all the relevant code and full instructions on how to run it

## Software versions

* **pact-ruby-standalone:** pact-1.69.0, pact-1.70.0
* **OS**: e.g. Mac OSX 10.14.6

## Expected behaviour

Running pact-publish command returns shows help/usage.

## Actual behaviour

Produces a rubygems error.

## Steps to reproduce

Running: $ /$(pwd)/bin/pact-publish

## Relevent log files

Command gives the following output:
/$(pwd)/pact/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundoler/setup (LoadError)
  from /$(pwd)/pact/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'

**Comment by mefellows** [comment]
The line that has `bundoler` looks suspicious. Have you modified any of the source?

**Comment by heretogo** [comment]
No, I have not.

**Comment by mefellows** [comment]
This commit is to blame. Looks like a typo snuck in: 926e87e2df7a248d9169e731951fc9ab1dc06c6b

**Comment by bethesque** [comment]
Fixed in v1.70.1

**Comment by heretogo** [comment]
Thank you.

**Comment by heretogo** [comment]
Can you please push the tag to trigger the release build?

**Comment by bethesque** [comment]
Apologies. I had, but the script didn't complete for an unrelated reason. Pushing again.
