### ISSUE TITLE
Runtime regex error on failing API test

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-ruby-standalone#47]
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [x] Upgraded to the latest version of the relevant libraries
* [x] Checked to see if the issue has already been raised
* [x] Created an executable example that demonstrates the issue using either:
  * a Dockerfile
  * a fork of https://github.com/pact-foundation/pact-ruby-standalone-e2e-example
  * a Git repository with a Travis or Appveyor (or similar) build
  * a gist with all the relevant code and full instructions on how to run it

## Software versions

* **pact-ruby-standalone:** eg 1.82.0
* **OS**: e.g. Mac OSX 10.14.4

First discovered on linux: `Linux eb7f63ba7ce0 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 Linux`

## Expected behaviour

When an API with an array body and matchers on a specific element (e.g. `"$.body.data[*].actions[0].href"`) is peresent, but the array body does not match,
I expect an error + diff showing that the expected response was not matching the actual response.

It very much confused me, as it looked like an issue with the _contract_ and not the response from the provider itself. 

## Actual behaviour

```
Verifying a pact between Foo and Bar
  Given there is a PDF for the first thing
    A request for a list of things
      with GET /foo
        returns a response which
WARN: Skipping set up for provider state 'there is a PDF for the first thing' for consumer 'Foo' as there is no --provider-states-setup-url specified.
127.0.0.1 - - [24/Mar/2020:09:44:52 +1100] "GET /foo HTTP/1.1" 200 - 0.0007
          has status code 200
          has a matching body (FAILED - 1)

Failures:

  1) Verifying a pact between Foo and Bar Given there is a PDF for the first thing A request for a list of things with GET /foo returns a response which has a matching body
     Failure/Error: expect(response_body).to match_term expected_response_body, diff_options, example

     RuntimeError:
       Sorry, ".*" is too vague, try setting a range: ".{0,3}"

1 interaction, 1 failure

Failed interactions:

* A request for a list of things given there is a PDF for the first thing
```

## Steps to reproduce

https://github.com/pact-foundation/pact-ruby-standalone-e2e-example/tree/repro/regex-too-vague-on-provider-failure

## Relevant log files

[foo-bar-mock-service.log](https://github.com/pact-foundation/pact-ruby-standalone/files/4372261/foo-bar-mock-service.log)
[pact.log](https://github.com/pact-foundation/pact-ruby-standalone/files/4372262/pact.log)

**Comment by bethesque** [comment]
This fixes it. Unfortunately, I know the unpack regexps is in there for a reason, but no test fails when I do this. Bad work, past Beth.

```
# expected_array = expected_size.times.collect{ Pact::Term.unpack_regexps(array_like.contents) }
expected_array = expected_size.times.collect{ array_like.contents }
```

**Comment by mefellows** [comment]
Awesome, thanks Beth!
