### ISSUE TITLE
pact-1.82.1-linux-x86_64.tar.gz Checksum seems to be broken.

### ISSUE THREAD

**Issue by ChristianKis** [pact-foundation/pact-ruby-standalone#49]
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [ ] Upgraded to the latest version of the relevant libraries
* [X] Checked to see if the issue has already been raised
* [ ] Created an executable example that demonstrates the issue using either:
  * a Dockerfile
  * a fork of https://github.com/pact-foundation/pact-ruby-standalone-e2e-example
  * a Git repository with a Travis or Appveyor (or similar) build
  * a gist with all the relevant code and full instructions on how to run it

## Software versions

* **pact library:** eg pact-js 9.9.2
pact-node ^10.8.0
* **OS**: Linux

## Expected behaviour

In-house CI installs pact and uses locally saved resource for postinstall script.

## Actual behaviour

Build fails with message: 
Error while installing binary: Postinstalled Failed Unexpectedly: Error: Error while installing binary: Extraction failed for <xyz>/node_modules/@pact-foundation/pact-node/standalone/pact-1.82.1-linux-x86_64.tar.gz: Error: Error while installing binary: Checksum rejected for file 'pact-1.82.1-linux-x86_64.tar.gz' with checksum pact-1.82.1-linux-x86_64.tar.gz.checksum

## Steps to reproduce

I've edited package json to 
{
"pact_binary_location": "MYPATH"
}

and downloaded the artifacts from: https://github.com/pact-foundation/pact-ruby-standalone/releases/tag/v1.82.1

-------------------

Am I missing something? Or the checksum in this artifact is broken?

Thanks for your help.

**Comment by bethesque** [comment]
Maybe it is! Try 1.82.2

**Comment by bethesque** [comment]
Updating it https://github.com/pact-foundation/pact-node/pull/220

**Comment by ChristianKis** [comment]
Thanks, works now, although I'm still using 1.82.1. 
Strange, maybe the issue was on my side in my npm cache.
