### ISSUE TITLE
Uanble to run the pact-mock-service on Mac 10.15 version

### ISSUE THREAD

**Issue by PGhalke** [pact-foundation/pact-ruby-standalone#53]
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [ X] Upgraded to the latest version of the relevant libraries
* [X ] Checked to see if the issue has already been raised
* [ ] Created an executable example that demonstrates the issue using either:
  * a Dockerfile
  * a fork of https://github.com/pact-foundation/pact-ruby-standalone-e2e-example
  * a Git repository with a Travis or Appveyor (or similar) build
  * a gist with all the relevant code and full instructions on how to run it

## Software versions

* **pact-ruby-standalone:** pact-1.84.0
* **OS**: e.g. Mac OSX 10.15 catalina

## Expected behaviour

$ ./pact-mock-service --help start
should have started the mock service.

 

## Actual behaviour

**$ ./pact-mock-service --help start**
ended with the error:
**$ ./pact-mock-service --help start**
/pact/lib/ruby/bin/ruby: line 6: /pact/lib/ruby/bin.real/ruby: No such file or directory

## Steps to reproduce

I was trying to work with the Pact-Mock-Server as per the instructions given in the ReadMe at 
https://github.com/pact-foundation/pact-ruby-standalone/releases/tag/v1.84.0

1. Downloaded the pact tar available for Mac OS in the link mentioned above, which is pact-1.84.0-osx.tar.gz.
2. Mac's Achive Utility tools untars the above mentioned tar into the folder with structure
  pact
 pact/bin/
 pact/lib/
Readme.md

3. After the untar, when i try to execute the command
**$ ./pact-mock-service --help start**
/pact/lib/ruby/bin/ruby: line 6: /Users/preethighalke/pact/lib/ruby/bin.real/ruby: No such file or directory
the command fails with the above error.

## Relevent log files
NA

**Comment by PGhalke** [comment]
@bethesque  FYI. ^^

**Comment by mefellows** [comment]
So on my Mac (osx 10.15.4) running the exact commands described in that standalone release work (running from `/tmp`):

```
curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.84.0/pact-1.84.0-osx.tar.gz
tar xzf pact-1.84.0-osx.tar.gz
cd pact/bin
./pact-mock-service --help start
./pact-provider-verifier --help verify
```

Result:

![out](https://user-images.githubusercontent.com/53900/82275610-8b6d6c80-99c6-11ea-88f8-c38c69cc256e.gif)

**Comment by mefellows** [comment]
As an aside, this package is used by many of our tools (e.g. Pact JS, Pact Go, Pact .NET). If the package didn't work on a Mac, we would have found out by now.

So it is likely something related to your configuration.

Could you please provide a way for us to reproduce your issue?

**Comment by PGhalke** [comment]
Thanks @mefellows  for the update, i tried to exactly do the steps you mentioned above and now it works.

The only difference was earlier I used the Archive Utility tool to extract the tar contents and run the command, unlike now where i used "tar xzf <file name>"

**Comment by PGhalke** [comment]
I tried extracting the tar again with Archive utility and i see the issue happening again

(base) Preethis-MBP:~ preethighalke$ cd Downloads/pact/bin/
(base) Preethis-MBP:bin preethighalke$ ./pact-mock-service --help start
Killed: 9
(base) Preethis-MBP:bin preethighalke$ ./pact-mock-service --help start
/Users/preethighalke/Downloads/pact/lib/ruby/bin/ruby: line 6: /Users/preethighalke/Downloads/pact/lib/ruby/bin.real/ruby: No such file or directory
(base) Preethis-MBP:bin preethighalke$

so looks like we might have to use the "tar" command to untar the package, which make it work.

Many Thanks

**Comment by mefellows** [comment]
The issue seems to be related to a recent security change in Mac OSX.

Because you extracted the contents using the Archine Utility, somehow, OSX knows it was downloaded from the internet and is sandboxing the binary. I've seen this before with other downloadable files. You need to right-click and then open, but for this case, just install using the CLI.

![Screen Shot 2020-05-19 at 2 03 22 pm](https://user-images.githubusercontent.com/53900/82283392-9bdb1280-99d9-11ea-8bab-ba0421c6974e.png)

![Screen Shot 2020-05-19 at 2 03 13 pm](https://user-images.githubusercontent.com/53900/82283396-9f6e9980-99d9-11ea-8755-4152797be379.png)

**Comment by bethesque** [comment]
There is a brew version of the pact-ruby-standalone https://github.com/pact-foundation/homebrew-pact-ruby-standalone that would side step this issue

**Comment by PGhalke** [comment]
Thanks @mefellows  and @bethesque.
