### ISSUE TITLE
Running the standalone package inside of a ruby container fails

### ISSUE THREAD

**Issue by johnduhart** [pact-foundation/pact-ruby-standalone#56]
I've encountered something similar to #17, where running the standalone package inside of a container is failing. After spending a few hours troubleshooting I've managed to narrow down the problem. Example dockerfile to reproduce:

```dockerfile
FROM ruby:2.6

WORKDIR /opt

RUN curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.87.5/pact-1.87.5-linux-x86_64.tar.gz \
    && tar xzf pact-1.87.5-linux-x86_64.tar.gz
```

I'm currently getting the following error:

```
C:\temp\pact-standalone> docker run --rm -it pact-standalone:latest /opt/pact/bin/pact-mock-service --help
Could not find rake-13.0.1 in any of the sources
Run `bundle install` to install missing gems.
```

The cause of this appears to be the [`BUNDLE_APP_CONFIG`](https://github.com/infosiftr/docker-library-docs/blob/master/ruby/content.md#image-assumptions) set on the `ruby` container. Adding the follow to the Dockerfile fixes the problem:

```dockerfile
RUN echo "echo unset BUNDLE_APP_CONFIG" >> /opt/pact/lib/ruby/bin/ruby_environment
```

I don't know if this is something that needs to be fixed upstream or in this package, but at the very least I wanted to just document this issue for anyone else that may encounter this.

**Comment by mefellows** [comment]
Thanks. This is a known issue and is documented _somewhere_ (we've had similar issues with other environment variables). It probably makes sense to explicitly unset this variable in the entry scripts in this repository.

**Comment by johnduhart** [comment]
Looks like #50 fixed this, but for batch files.

**Comment by YOU54F** [comment]
Hey @johnduhart 

Just came across this issue during the upgrade to ruby 3.2.2 as I wanted to use it as a builder image, as it was quicker than builder ruby from source.

https://github.com/pact-foundation/pact-ruby-standalone/blob/b8c1020f2d8a7d8a624cb23b6fb5da1639932e3f/.cirrus.yml#L13-L27

Applying the change to the `.sh` scripts and solved the error 🚀

**Comment by YOU54F** [comment]
Will get it updated, and out :)

**Comment by bethesque** [comment]
I would not use the standalone inside of a container. it will be super slow. Much better to actually install ruby and the native gem.
