### ISSUE TITLE
Getting Openssl Error while using Pact Ruby Standalone CLI 'can-i-deploy' utility

### ISSUE THREAD

**Issue by samzee** [pact-foundation/pact-ruby-standalone#58]
I have pact broker setup inside a k8s cluster, while trying to use 'can-i-deploy' utilty from command line getting below error, any help is much appreciated, tired using the $SSL_CERT_FILE & $SSL_CERT_DIR solution  it didn't helped
Error Making request - openSSL::SSL::SSLError SSL_connect returned=1 errno=0 stage=SSLV3 read server
Certificate B: certificate verify failed I:pact/lib/vendor/ruby/2.2.0/gems/pactbroker-client-2.29.1/lib/pact_broker/client/matrix.rb:13 in `get', attempt 1 of 3

**Comment by bethesque** [comment]
It sounds like you're using a self signed certificate. Please follow this example https://github.com/DiUS/pact_broker-docker/blob/master/docker-compose.yml

**Comment by YOU54F** [comment]
Please re-raise if you are still having an issue after following instructions above, thanks!
