### ISSUE TITLE
No valid JSON for pact-broker list-latest-pact-versions

### ISSUE THREAD

**Issue by siad007** [pact-foundation/pact-ruby-standalone#59]
## Software versions

* **pact-ruby-standalone:** 1.88.15

## Expected behaviour
`pact-broker list-latest-pact-versions --output=json` should return valid JSON.
```
pact/bin/pact-broker list-latest-pact-versions --output=json --broker-base-url=https://test.pact.dius.com.au --broker-username=dXfltyFMgNOFZAxr8io9wJ37iUpY42M --broker-password=O5AIZWxelWbLvqMd8PkAVycBJh2Psyg1
```

## Actual behaviour
`=>` is not valid and should be exchanged by `:`
```
{"pacts"=>[{"createdAt"=>"2020-04-30T07:44:38+00:00", "_embedded"=>{"consumer"=>{"name"=>"action-modeler", "_embedded"=>{"version"=>{"number"=>"1.0.1588232666", "_links"=>{"self"=>{"title"=>"Version", "name"=>"1.0.1588232666", "href"=>"https://test.pact.dius.com.au/pacticipants/action-modeler/versions/1.0.1588232666"}}}}, "_links"=>{"self"=>{"href"=>"https://test.pact.dius.com.au/pacticipants/action-modeler"}}}, "provider"=>{"name"=>"customdata-association", "_links"=>{"self"=>{"href"=>"https://test.pact.dius.com.au/pacticipants/customdata-association"}}}}, "_links"=>{"self"=>[{"href"=>"https://test.pact.dius.com.au/pacts/provider/customdata-association/consumer/action-modeler/latest"}, {"href"=>"https://test.pact.dius.com.au/pacts/provider/customdata-association/consumer/action-modeler/version/1.0.1588232666"}]}}, {"createdAt"=>"2020-05-24T13:11:09+00:00", "_embedded"=>{"consumer"=>
```

## Steps to reproduce

Your bug will be fixed in our free time, so help us to help you, and make it as easy as possible for us to reproduce the issue. Issues that take longer to reproduce are less likely to be fixed quickly. Please provide a Dockerfile or git repository + build, with instructions on how to reproduce the issue.

## Relevent log files

Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link from a gist).

**Comment by bethesque** [comment]
Thanks @siad007. Would you mind moving the issue to https://github.com/pact-foundation/pact_broker-client ?

**Comment by bethesque** [comment]
Don't worry, it was such an easy fix, I just did it. The new release will be out by the time you read this.

**Comment by siad007** [comment]
Many thx
