### ISSUE TITLE
Release 1.4.0 is missing... the release

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-ruby-standalone#6]
See https://github.com/pact-foundation/pact-ruby-standalone/releases/tag/v1.4.0 - we seem to be missing the distribution :)

**Comment by mefellows** [comment]
Seems to be related to https://travis-ci.org/pact-foundation/pact-ruby-standalone

**Comment by mefellows** [comment]
Was related to an outdated dependency (`pact-provider-proxy`) which was recently removed from the verifier.

Tagged a new release `v1.4.2`, and have been able to package it successfully into pact-go, closing.

**Comment by bethesque** [comment]
Thanks.
