### ISSUE TITLE
Upgrade to Travelling Ruby 2.4

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-ruby-standalone#63]
https://github.com/phusion/traveling-ruby/issues/88

**Comment by regularcoder** [comment]
Will you accept a PR for this? Is it just a matter of updating https://github.com/pact-foundation/pact-ruby-standalone/blob/master/tasks/package.rake?

**Comment by bethesque** [comment]
Gladly. It's not completely straightforward, because not all the operating systems have an updated distribution. I started a branch here (that doesn't work) https://github.com/pact-foundation/pact-ruby-standalone/tree/chore/upgrade-to-ruby-2-4-10

**Comment by bethesque** [comment]
Done.
