### ISSUE TITLE
Add support for arm64 on Linux

### ISSUE THREAD

**Issue by maatthc** [pact-foundation/pact-ruby-standalone#70]
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [x] Upgraded to the latest version of the relevant libraries
* [x] Checked to see if the issue has already been raised
* [x] Created an executable example that demonstrates the issue using either:
  * a Dockerfile
  * a fork of https://github.com/pact-foundation/pact-ruby-standalone-e2e-example
  * a Git repository with a Travis or Appveyor (or similar) build
  * a gist with all the relevant code and full instructions on how to run it

## Software versions

* **OS**: aarch64 aarch64 aarch64 GNU/Linux

## Expected behaviour

Would be nice to have support to aarch64 as Amazon and Oracle Cloud have good offers for instances on this platform.

## Actual behaviour

Available executable are not compatible with ARM.

## Steps to reproduce
Try to run any of the released packages on Arm-based **AWS** Graviton2 processors on EC2.

## Relevent log files

Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link from a gist).

**Comment by bethesque** [comment]
Which part of the ruby standalone are you interested in using? eg. the pact broker CLI, or the pact mock service/verifier.

**Comment by maatthc** [comment]
The ideal would be to have support to everything.

**Comment by bethesque** [comment]
The reason I ask is that the mock service and verifier are being replaced in each of the languages by a shared rust lib, so the "pact" commands in the standalone are pretty much legacy now. The pact-broker CLI commands have their own [docker image](https://github.com/pact-foundation/pact-ruby-cli). So it would help to know which parts of the standalone you're using, and for which language, because they'll need to be solved differently.

**Comment by p0deje** [comment]
It would be nice to at least be able to install `pact-node` on Linux arm64 so that the images could be used on M1.

**Comment by bethesque** [comment]
Travelling Ruby (what we use to package up the pact-ruby-standalone) is not being maintained any more, and is unlikely to ever be supported for M1. We're transitioning all the pact clients away from that and onto a shared rust library. The Rust library will be supported on M1 (but I don't know the timing on this). @mefellows and @TimothyJones might be able to add more information about this. 

I believe theres is a work around for the M1 issue however, as one of my colleagues is currently running the standalone on her M1. Try searching in the pact-js issues or asking in the #pact-js Slack channel.

**Comment by mefellows** [comment]
You need to install it through Rosetta mode.

**Comment by mefellows** [comment]
For "everything" support it will unlikely be possible via the standalone, as the maintainer if that library has basically stated they will no longer be adding major updates.

You could install the bits you need via rubygems or we could add arm support to the docker image (ruby itself can run on arm, so we'd just need to build an arm image)

**Comment by timReynolds** [comment]
For those trying to build an image which includes pact on M1 Macs you specify the platform;
```
docker build --platform linux/amd64  .
```

Solution is outline in detail [here](https://forums.docker.com/t/run-x86-intel-and-arm-based-images-on-apple-silicon-m1-macs/117123/2).

**Comment by SanjayaKumarSahoo** [comment]
are we going to fix the issue?

**Comment by SanjayaKumarSahoo** [comment]
Are we going to fix this issue, we are looking at this as urgent. Any help on this would be appreciable.

**Comment by TimothyJones** [comment]
Does the docker command that Tim linked above not work for you? What problems are you encountering?

**Comment by YOU54F** [comment]
☝🏾 to that linked issue, I have got some very alpha arm64 osx and darwin standalone packages you can trial

https://github.com/YOU54F/pact-ruby-standalone/releases/tag/v3.1.2.2-alpha

Note these aren't official builds so your mileage might vary and you shouldn't rely on them at the moment until we get some feedback

## Direct Download

`curl -fsSL https://raw.githubusercontent.com/you54f/pact-ruby-standalone/ruby_3.2.2_upgrade/install.sh | bash`

`wget -q https://raw.githubusercontent.com/you54f/pact-ruby-standalone/ruby_3.2.2_upgrade/install.sh -O- | bash`

Script here

https://github.com/YOU54F/pact-ruby-standalone/blob/ruby_3.2.2_upgrade/install.sh

## HomeBrew

https://github.com/you54f/homebrew-pact-ruby-standalone

```
brew tap you54f/pact-ruby-standalone
brew install pact-ruby-standalone
```

## FlatPak

https://github.com/YOU54F/flatpak

## Scoop

`scoop bucket add pact https://github.com/you54f/scoop`
`scoop install pact`

https://github.com/YOU54F/scoop

## Choco

`choco install pact --version=0.0.1`

https://github.com/YOU54F/choco

**Comment by YOU54F** [comment]
You want it?

You got it!

Now, just don't break it 😂
