### ISSUE TITLE
contract_requiring_verification_published event not available in create-webhook command

### ISSUE THREAD

**Issue by praveen-em** [pact-foundation/pact-ruby-standalone#71]
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [x] Upgraded to the latest version of the relevant libraries
* [x] Checked to see if the issue has already been raised
* [ ] Created an executable example that demonstrates the issue using either:
  * a Dockerfile
  * a fork of https://github.com/pact-foundation/pact-ruby-standalone-e2e-example
  * a Git repository with a Travis or Appveyor (or similar) build
  * a gist with all the relevant code and full instructions on how to run it

## Software versions
pact-ruby-standalone: pact-1.88.79-linux-x86_64.tar.gz

## Expected behaviour
contract_requiring_verification_published event for webhook is excellent feature. It would be great if we have ability to create webhooks for this event through create-webhook command from cli tool. 

## Actual behaviour
webhook for contract_requiring_verification_published event cannot be created through create-webhook. The only option seems to be through HAL API browser. Is there any plan to add this event to create-webhook in near future? 

## Steps to reproduce
NA

## Relevent log files
NA

Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link from a gist).

**Comment by bethesque** [comment]
Hi, it's available but feature toggled. Set the environment variable `PACT_BROKER_FEATURES=contract_requiring_verification_published`. I'll remove the feature toggle and get a new version out.

**Comment by bethesque** [comment]
Latest version is out with the feature toggle removed.

**Comment by praveen-em** [comment]
Great! Thanks Beth for the new release. At some point, it would be good to update [this documentation](https://docs.pact.io/pact_broker/client_cli/readme/#webhooks) as well.

**Comment by bethesque** [comment]
Thanks for the reminder. I've regenerated those docs now.
