### ISSUE TITLE
ERROR main pact_stub_server:   - Failed to load pact file: Expected a "." or "[" instead of "'" in path expression "com-spf-token']" at index 13 - pacts/myPact.json

### ISSUE THREAD

**Issue by CharlyApps** [pact-foundation/pact-ruby-standalone#81]
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [ X] Upgraded to the latest version of the relevant libraries
* [ X] Checked to see if the issue has already been raised
* [ ] Created an executable example that demonstrates the issue using either:
  * a Dockerfile
  * a fork of https://github.com/pact-foundation/pact-ruby-standalone-e2e-example
  * a Git repository with a Travis or Appveyor (or similar) build
  * a gist with all the relevant code and full instructions on how to run it

## Software versions

* **pact-ruby-standalone:** Latest release
* **OS**: e.g. Mac OSX 12.4

## Expected behaviour

Hi, for some reason, last Monday I update from 1.88.77 to latest version, from that point I can't start the pact_stub_server it keeps throwing an error:

main pact_stub_server: - Failed to load pact file: Expected a "." or "[" instead of "'" in path expression "com-spf-token']" at index 13 - pacts/myPact.json

then I go back to 1.88.77 and somehow the error persist, try in older computers that haven't update to latest version and works like a charm, the pact data having the issue is this

"$.headers['company.com-spf-token']": {
"match": "type"
}

**Comment by bethesque** [comment]
Sorry, I know it's confusing having all these different implementations around, but the issue you have is with this project https://github.com/pact-foundation/pact-stub-server Can you raise the issue there please.

**Comment by bethesque** [comment]
Oh, my bad `1.88.77` is a pact-ruby-standalone version - the `main pact_stub_server` fooled me into thinking it was the other implementation. As noted in the issue raising checklist, please provide a reproducible example using the https://github.com/pact-foundation/pact-ruby-standalone-e2e-example project.

**Comment by CharlyApps** [comment]
After several tests, I found the issue is happening in [pact-stub-server](https://github.com/pact-foundation/pact-stub-server), I haven't been able to fix it but I found a workaround, it seems the issue was introduced after 0.5.0 and my best guess is that is related in how the JSON pacts are interpreted.
