### ISSUE TITLE
Checksum error during npm install pact-node

### ISSUE THREAD

**Issue by immo-huneke-zuhlke** [pact-foundation/pact-ruby-standalone#82]
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [x] Upgraded to the latest version of the relevant libraries
* [x] Checked to see if the issue has already been raised
* [ ] Created an executable example that demonstrates the issue using either:
  * a Dockerfile
  * a fork of https://github.com/pact-foundation/pact-ruby-standalone-e2e-example
  * a Git repository with a Travis or Appveyor (or similar) build
  * a gist with all the relevant code and full instructions on how to run it

## Software versions

* **pact library:** pact-node 10.17.6
* **pact-ruby-standalone:** 1.89.02-rc1 for win32
* **OS**: Windows 10

## Expected behaviour

Successful installation

## Actual behaviour

```
PS C:\CCShare\Projects\pact-demo> npm install --save '@pact-foundation/pact-node'
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code 1
npm ERR! path C:\CCShare\Projects\pact-demo\node_modules\@pact-foundation\pact-node
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node postinstall.js
npm ERR! Installing Pact Standalone Binary for win32.
npm ERR! Downloading Pact Standalone Binary v1.89.02-rc1 for platform win32 from https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.89.02-rc1/pact-1.89.02-rc1-win32.zip
npm ERR! Please note: we are tracking this download anonymously to gather important usage statistics. To disable tracking, set 'pact_do_not_track: true' in your package.json 'config' section.
npm ERR! Finished downloading binary to C:\CCShare\Projects\pact-demo\node_modules\@pact-foundation\pact-node\standalone\pact-1.89.02-rc1-win32.zip
npm ERR! Extracting binary from C:\CCShare\Projects\pact-demo\node_modules\@pact-foundation\pact-node\standalone\pact-1.89.02-rc1-win32.zip.
npm ERR! Error: Error while installing binary: Postinstalled Failed Unexpectedly: Error: Error while installing binary: Extraction failed for C:\CCShare\Projects\pact-demo\node_modules\@pact-foundation\pact-node\standalone\pact-1.
89.02-rc1-win32.zip: Error: Error while installing binary: Checksum rejected for file 'pact-1.89.02-rc1-win32.zip' with checksum pact-1.89.02-rc1-win32.zip.checksum
npm ERR!     at throwError (C:\CCShare\Projects\pact-demo\node_modules\@pact-foundation\pact-node\standalone\install.js:42:11)
npm ERR!     at C:\CCShare\Projects\pact-demo\node_modules\@pact-foundation\pact-node\standalone\install.js:327:16
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\imhu01\AppData\Local\npm-cache\_logs\2022-08-11T08_29_11_456Z-debug-0.log

```
## Steps to reproduce

First ensure that Visual Studio Community (or equivalent) with C/C++ support is installed.
Then install node-gyp via `npm install --global`.
Then in a project folder install `@pact-foundation/pact` using `npm install --save '@pact-foundation/pact'`
Then attempt `npm install --save '@pact-foundation/pact-node'`

## Relevant log files

Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link from a gist).

**Comment by immo-huneke-zuhlke** [comment]
I have used the debugger in IntelliJ IDEA and ascertained that at the time the sumchecker is invoked, both the checksum file and the zip file are in the standalone directory. But by the time the sumchecker returns its result (showing that there is a difference in the checksums) the zip file has disappeared. I wonder therefore whether there is a race condition between the code that unpacks and deletes the zip file, and the code that compiles the checksum.

**Comment by YOU54F** [comment]
@pact-foundation/pact includes pact-js-core and the standalone binaries.

Pact-node was renamed to pact-js-core

https://github.com/pact-foundation/pact-js-core

You should only need to install one, most likely not the js-core

as a note, pact would be traditionally saved as a dev dependency too

**Comment by immo-huneke-zuhlke** [comment]
Thanks for your advice. I will try that then. It is confusing that the pact tutorial refers to pact-node and in fact will not run without it - but I'll try to see whether pact-js-core can be used instead.

**Comment by immo-huneke-zuhlke** [comment]
FYI it wasn't possible to install @pact-foundation/pact-js-core - because of the registry cache being used here. However, I may be able to install directly from a tarball if it turns out that I need this as well as @pact-foundation/pact.

**Comment by immo-huneke-zuhlke** [comment]
In fact the tests ran successfully without pact-node or pact-js-core. Thanks for setting me straight!

**Comment by YOU54F** [comment]
Hey @immo-huneke-zuhlke could you confirm which tutorial and we can look to getting it updated

> It is confusing that the pact tutorial refers to pact-node

Thanks for trying it out, raising an issue, and getting sorted for now.

If you aren't already, feel free to join us in the Pact Slack group slack.pact.io

**Comment by immo-huneke-zuhlke** [comment]
Hi Yousaf,

Thanks for getting back to me. I was referring to this:

https://docs.pact.io/5-minute-getting-started-guide

Just over half-way down, there is a heading “Run the consumer Tests”. Under it there’s a frame with Console and Shell tabs. I grabbed the package.json file by switching to the shell tab!

As a matter of fact, it would be great if this tutorial could present (or at least reference) the whole recommended project/module structure, including the segregation of code modules into source and test source. I had to guess in many cases; in fact the code snippets presented don’t even always show the file names or paths, and without a package.json you can’t even get the project to build, let alone run the tests.

Thanks again!

Best regards,
Immo

From: Yousaf Nabi ***@***.***>
Reply to: pact-foundation/pact-ruby-standalone ***@***.***>
Date: Thursday, 11 August 2022 at 11:28
To: pact-foundation/pact-ruby-standalone ***@***.***>
Cc: Immo Huneke ***@***.***>, Mention ***@***.***>
Subject: Re: [pact-foundation/pact-ruby-standalone] Checksum error during npm install pact-node (Issue #82)


Hey @immo-huneke-zuhlke<https://github.com/immo-huneke-zuhlke> could you confirm which tutorial and we can look to getting it updated

It is confusing that the pact tutorial refers to pact-node

Thanks for trying it out, raising an issue, and getting sorted for now.

If you aren't already, feel free to join us in the Pact Slack group slack.pact.io
