### ISSUE TITLE
INFO logging to stdout breaks JSON formatter

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-ruby-standalone#9]
I recently upgraded Pact Go to `1.21.0` and the Pact integration tests started failing on Provider Verification.

I noticed the issue only happened when we enabled publishing to the broker, and have been able to trace the source of the problem to the following change https://github.com/pact-foundation/pact-ruby/commit/e0dad2761e1fb6005aa2ad2daffdb4eaeb8687c9#diff-2aa19ad532bad3f2050ce3b3aff47b0dR92.

What's happened is that there is stuff logged to stderr and stdout. The current assumption is that the JSON response should be taken from stdout, so any extra logging to this stream will break JSON parsing. To my knowledge, only the Golang implementation uses this feature, hence why we're only finding it out now.

The simple fix is to log this to stderr, log to disk or remove the message altogether.

_NOTE_: I didn't raise on the upstream pact project because contextually it belongs here, even though the breaking change is in that library. This does raise another question though, as it's going to be hard to track changes across all of the gem files that do this sort of thing. Should we look to handle output streams in this package based on context/flags? e.g. if JSON is the output format, we can't have other stuff being logged in the same stream.

**Comment by bethesque** [comment]
I just need to change it to use the configured output stream rather than $stdout directly. I've already got logic to send the messages to stderr when we're using JSON output here: https://github.com/pact-foundation/pact-ruby/blob/master/lib/pact/provider/pact_spec_runner.rb#L71

**Comment by bethesque** [comment]
Upgrade to v1.22.0 standalone.
