### ISSUE TITLE
Is this still recommended for use? 

### ISSUE THREAD

**Issue by ryancurrah** [pact-foundation/pact-ruby-standalone#95]
Doesn't seem to be updated anymore. I am wondering if this is still recommended for use?

**Comment by YOU54F** [comment]
It depends on your use-case,

we recommend using the rust based tools for a mock service or verifier functionality

https://docs.pact.io/implementation_guides/cli#pact-ruby-standalone

the pact-cli (broker client) functionality is available in the docker pact cli.

some pact client libraries are still using the pact-ruby-standalone, and are in various stages of progress of migrating to the rust core.

Travelling ruby which we use for packaging the standalone is stuck on Ruby 2.4 which is EOL as of a couple of years ago

What are your exact needs, and we can help advise

>Doesn't seem to be updated anymore

Gems are updated with dependabot, security scanning is done with trivy and the API's are generally stable so there isn't much need for functional updates, so it is all relative :)

**Comment by ryancurrah** [comment]
I think that answers it. Thank you!

**Comment by YOU54F** [comment]
No worries @ryancurrah 🙌🏾
