### ISSUE TITLE
Pact-ruby-standalone not compatible with alpine glibc-2.35-r0

### ISSUE THREAD

**Issue by bhasden** [pact-foundation/pact-ruby-standalone#96]
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [x] Upgraded to the latest version of the relevant libraries
* [x] Checked to see if the issue has already been raised
* [x] Created an executable example that demonstrates the issue using either:
  * a Dockerfile
  * a fork of https://github.com/pact-foundation/pact-ruby-standalone-e2e-example
  * a Git repository with a Travis or Appveyor (or similar) build
  * a gist with all the relevant code and full instructions on how to run it

## Software versions

* **pact library:** 
* **pact-ruby-standalone:** 1.91.0
* **OS**: Windows 11 Pro 22H2 Build 22621.1105

## Expected behaviour

Pact tools installed correctly

## Actual behaviour

Pact tools do not run and receive error
`/pact/lib/ruby/bin/ruby: line 6: /pact/lib/ruby/bin.real/ruby: cannot execute: required file not found`

## Steps to reproduce

See [gist](https://gist.github.com/bhasden/455449a7c3da7e3de294f6c9d4e72c7e)

Please let me know if you need more information/none of this is relevant/I'm a moron and missing something obvious.

**Comment by YOU54F** [comment]
Thanks for the issue and gist, you need to install `gcompat`

top run is after adding `apk add gcompat`

<img width="716" alt="Screenshot 2023-04-18 at 23 03 27" src="https://user-images.githubusercontent.com/19932401/232915158-93a94851-ffee-4673-9c1c-a1525a0a5cf5.png">

I came across the issue last night

```
FROM golang:1.20.2-alpine3.17

WORKDIR ../

ENV PACT_VERSION=1.91.0 \
    GLIBC_VERSION=2.35-r0

# Glibc for alpine. Pact has a dependancie on glibc in its ruby implementation, musl-dev from base image is not compatible
# https://github.com/pact-foundation/pact-ruby-standalone/wiki/Using-the-pact-ruby-standalone-with-Alpine-Linux-Docker
RUN apk --no-cache add gcompat bash=5.2.15-r0 \
     && wget -O /etc/apk/keys/sgerrand.rsa.pub -q https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
     && wget -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk \
     && apk --no-cache --force-overwrite add glibc-${GLIBC_VERSION}.apk

# Pact binaries and related dependencies
RUN wget -q https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v${PACT_VERSION}/pact-${PACT_VERSION}-linux-x86_64.tar.gz \
     && tar xzf pact-${PACT_VERSION}-linux-x86_64.tar.gz \
     && rm -rf pact-${PACT_VERSION}-linux-x86_64.tar.gz \
     && ln -s /pact/bin/* /usr/local/bin

WORKDIR $GOPATH
```

**Comment by YOU54F** [comment]
Closing, feel free to re-raise if you still have issues after trying the suggested work around

**Comment by YOU54F** [comment]
For alpine arm64 flavour I needed the addition of `libc6-compat`

```
FROM arm64v8/alpine

WORKDIR ../

ENV PACT_VERSION=2.0.0

RUN apk --no-cache add gcompat libc6-compat bash
RUN wget -q https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v${PACT_VERSION}/pact-${PACT_VERSION}-linux-arm64.tar.gz \
     && tar xzf pact-${PACT_VERSION}-linux-arm64.tar.gz \
     && rm -rf pact-${PACT_VERSION}-linux-arm64.tar.gz \
     && ln -s /pact/bin/* /usr/local/bin

ENTRYPOINT ["pact-mock-service"]
```

For your x86_64 variant, it seems you can do the same, use `gcompat` and `libc6comapt` or `glibc` as shown above

```
FROM golang:1.20.2-alpine3.17

WORKDIR ../

ENV PACT_VERSION=2.0.0
RUN apk --no-cache add gcompat libc6-compat bash
RUN wget -q https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v${PACT_VERSION}/pact-${PACT_VERSION}-linux-x86_64.tar.gz \
     && tar xzf pact-${PACT_VERSION}-linux-x86_64.tar.gz \
     && rm -rf pact-${PACT_VERSION}-linux-x86_64.tar.gz \
     && ln -s /pact/bin/* /usr/local/bin

ENTRYPOINT ["pact-mock-service"]
```

**Comment by YOU54F** [comment]
For any other users finding their way here - the wiki is now updated to reflect

 https://github.com/pact-foundation/pact-ruby-standalone/wiki/Using-the-pact-ruby-standalone-with-Alpine-Linux-Docker
